if(ENABLE_IPO)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT ipo_supported OUTPUT output)
  if(ipo_supported)
    message(${BoldBlue} "-- IPO supported.")
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  else()
    message(${BoldYellow} "-- IPO is not supported: ${output}")
  endif()
endif()
